package entity;
// Generated 08-abr-2019 20:45:14 by Hibernate Tools 4.3.1

/**
 * Login generated by hbm2java
 */
public class Login implements java.io.Serializable {

    private Integer idLogin;
    private String username;
    private String password;
    private String type;

    public Login() {
    }

    public Login(String username, String password, String type) {
        this.username = username;
        this.password = password;
        this.type = type;
    }

    public Integer getIdLogin() {
        return this.idLogin;
    }

    public void setIdLogin(Integer idLogin) {
        this.idLogin = idLogin;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
